apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace:  grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: grade-submission-api
      app.kubernetes.io/env: frontend
      app.kubernetes.io/instance: work-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission-api
        app.kubernetes.io/env: frontend
        app.kubernetes.io/instance: work-test
    spec:
      containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
